/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Layout/AppHeader.vue')['default']
    AppPagination: typeof import('./src/components/Layout/AppPagination.vue')['default']
    AppSidebar: typeof import('./src/components/Layout/AppSidebar.vue')['default']
    DashboardCard: typeof import('./src/components/Dashboard/DashboardCard.vue')['default']
    DashboardCardSkeleton: typeof import('./src/components/Dashboard/DashboardCardSkeleton.vue')['default']
    DashboardSlot: typeof import('./src/components/Dashboard/DashboardSlot.vue')['default']
    OverviewGraph: typeof import('./src/components/Overview/OverviewGraph.vue')['default']
    OverviewList: typeof import('./src/components/Overview/OverviewList.vue')['default']
    OverviewListItem: typeof import('./src/components/Overview/OverviewListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
